name = "sm3-fortran"
version = "1.0.0"
license = "BSD-3-Clause"
author = "ZUO Zhihua"
maintainer = "zuo.zhihua@qq.com"
categories = ['SM3 Hash', '杂凑值', '哈希', '信息摘要', 'MD5']

[dependencies]
GmSSL = { path = "GmSSL" }
